<%@ Page Language="C#" MasterPageFile="~/site.master" AutoEventWireup="true" CodeFile="Admin.aspx.cs" Inherits="Admin" Title="管理员管理页面" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
  <asp:Label ID="lblName" runat="server" Text="站务通知" Visible="False"></asp:Label>
   <asp:Label ID="lblImgUrl" runat="server" Text="~/App_Themes/image/Smile.bmp" Visible="false"></asp:Label>
  <hr />
 各区帖子列表：<br />
    <asp:Label ID="lblMsg" runat="server"></asp:Label>
   <br/>
    站务管理区<br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4"
        ForeColor="#333333" GridLines="None"  AllowPaging="True" AutoGenerateDeleteButton="True" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowDeleting="GridView1_RowDeleting">
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <Columns>
            <asp:HyperLinkField DataNavigateUrlFields="noteId" DataNavigateUrlFormatString="Content.aspx?{0}"
                DataTextField="noteTitle" HeaderText="主题">
                <ItemStyle Width="500px" />
            </asp:HyperLinkField>
            <asp:BoundField DataField="userNick" HeaderText="作者">
                <ItemStyle Width="90px" />
            </asp:BoundField>
            <asp:BoundField DataField="contTime" HeaderText="发表时间">
                <ItemStyle Width="90px" />
            </asp:BoundField>
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <EditRowStyle BackColor="#999999" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    文化艺术区<br />
    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" CellPadding="4"
        ForeColor="#333333" GridLines="None"  AllowPaging="True" AutoGenerateDeleteButton="True" OnPageIndexChanging="GridView2_PageIndexChanging" OnRowDeleting="GridView2_RowDeleting">
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <Columns>
            <asp:HyperLinkField DataNavigateUrlFields="noteId" DataNavigateUrlFormatString="Content.aspx?{0}"
                DataTextField="noteTitle" HeaderText="主题">
                <ItemStyle Width="500px" />
            </asp:HyperLinkField>
            <asp:BoundField DataField="userNick" HeaderText="作者">
                <ItemStyle Width="90px" />
            </asp:BoundField>
            <asp:BoundField DataField="contTime" HeaderText="发表时间">
                <ItemStyle Width="90px" />
            </asp:BoundField>
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <EditRowStyle BackColor="#999999" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    信息技术区<br />
    <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" CellPadding="4"
        ForeColor="#333333" GridLines="None"  AllowPaging="True" AutoGenerateDeleteButton="True" OnPageIndexChanging="GridView3_PageIndexChanging" OnRowDeleting="GridView3_RowDeleting">
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <Columns>
            <asp:HyperLinkField DataNavigateUrlFields="noteId" DataNavigateUrlFormatString="Content.aspx?{0}"
                DataTextField="noteTitle" HeaderText="主题">
                <ItemStyle Width="500px" />
            </asp:HyperLinkField>
            <asp:BoundField DataField="userNick" HeaderText="作者">
                <ItemStyle Width="90px" />
            </asp:BoundField>
            <asp:BoundField DataField="contTime" HeaderText="发表时间">
                <ItemStyle Width="90px" />
            </asp:BoundField>
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <EditRowStyle BackColor="#999999" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    休闲娱乐区<br />
    <asp:GridView ID="GridView4" runat="server" AutoGenerateColumns="False" CellPadding="4"
        ForeColor="#333333" GridLines="None"  AllowPaging="True" AutoGenerateDeleteButton="True" OnPageIndexChanging="GridView4_PageIndexChanging" OnRowDeleting="GridView4_RowDeleting">
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <Columns>
            <asp:HyperLinkField DataNavigateUrlFields="noteId" DataNavigateUrlFormatString="Content.aspx?{0}"
                DataTextField="noteTitle" HeaderText="主题">
                <ItemStyle Width="500px" />
            </asp:HyperLinkField>
            <asp:BoundField DataField="userNick" HeaderText="作者">
                <ItemStyle Width="90px" />
            </asp:BoundField>
            <asp:BoundField DataField="contTime" HeaderText="发表时间">
                <ItemStyle Width="90px" />
            </asp:BoundField>
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <EditRowStyle BackColor="#999999" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    学习天地区<br />
    <asp:GridView ID="GridView5" runat="server" AutoGenerateColumns="False" CellPadding="4"
        ForeColor="#333333" GridLines="None"  AllowPaging="True" AutoGenerateDeleteButton="True" OnPageIndexChanging="GridView5_PageIndexChanging" OnRowDeleting="GridView5_RowDeleting">
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <Columns>
            <asp:HyperLinkField DataNavigateUrlFields="noteId" DataNavigateUrlFormatString="Content.aspx?{0}"
                DataTextField="noteTitle" HeaderText="主题">
                <ItemStyle Width="500px" />
            </asp:HyperLinkField>
            <asp:BoundField DataField="userNick" HeaderText="作者">
                <ItemStyle Width="90px" />
            </asp:BoundField>
            <asp:BoundField DataField="contTime" HeaderText="发表时间">
                <ItemStyle Width="90px" />
            </asp:BoundField>
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <EditRowStyle BackColor="#999999" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    投票管理<br />
    <asp:GridView ID="GridView6" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        CellPadding="4" CssClass="GridViewSty" ForeColor="#333333" GridLines="None" Width="709px" OnRowDeleting="GridView6_RowDeleting">
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <Columns>
            <asp:HyperLinkField DataNavigateUrlFields="SubjectId" DataNavigateUrlFormatString="ballot.aspx?{0}"
                DataTextField="SubjectName" HeaderText="投票主题">
                <ItemStyle Width="500px" />
            </asp:HyperLinkField>
            <asp:BoundField DataField="SumNumber" HeaderText="投票数">
                <ItemStyle Width="90px" />
            </asp:BoundField>
        </Columns>
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <EditRowStyle BackColor="#999999" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
    <br />
</asp:Content>

